In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/processed/cleaned_reviews.csv")

In [3]:
df.head()

,Product_name,Price,Rate,Review,Summary,full_review,sentiment,review_length,word_count
0,"Crompton 75 L Desert Air Cooler(White, Teal, A...","??10,499",5.0,Simply awesome,it's really worth every single penny. it works...,Simply awesome it's really worth every single ...,Positive,508,92
1,"Crompton 75 L Desert Air Cooler(White, Teal, A...","??10,499",4.0,Worth the money . Desert Cooler live up to the...,I bought Crompton Ozone 75 Desert Air Cooler i...,Worth the money . Desert Cooler live up to the...,Positive,548,112
2,"Crompton 75 L Desert Air Cooler(White, Teal, A...","??10,499",5.0,Worth every penny,GREAT packaging by seller. As this was the mos...,Worth every penny GREAT packaging by seller. A...,Positive,518,89
3,"Crompton 75 L Desert Air Cooler(White, Teal, A...","??10,499",5.0,Fabulous!,Delivery was delayed by two days except this e...,Fabulous! Delivery was delayed by two days exc...,Positive,414,69
4,"Crompton 75 L Desert Air Cooler(White, Teal, A...","??10,499",4.0,Nice product,A Good cooler by Crompton. The height of the c...,Nice product A Good cooler by Crompton. The he...,Positive,515,102

In [4]:
df.shape

(306316, 9)

In [5]:
text = df["full_review"].iloc[0]

print(text)

Simply awesome it's really worth every single penny. it works like one ton AC provided that your room has proper ventilation.  I generally keep cooler near to window so that it can pull fresh air from outside and as a result I get very cool air. one more suggestion,  please don't buy cooler which are equipped with a blower fan. Always go for the cooler equipped with metal fan like this one.  In one word, this Compton cooler is Amazing. if you find the review helpful, please thumps up. Happy summer! ????

In [6]:
text_lower = text.lower()

print(text_lower)

simply awesome it's really worth every single penny. it works like one ton ac provided that your room has proper ventilation.  i generally keep cooler near to window so that it can pull fresh air from outside and as a result i get very cool air. one more suggestion,  please don't buy cooler which are equipped with a blower fan. always go for the cooler equipped with metal fan like this one.  in one word, this compton cooler is amazing. if you find the review helpful, please thumps up. happy summer! ????

In [7]:
import re

sample = "Product is AMAZING!!! Worth ₹10,499... 100% recommended!!!"

print(sample)

Product is AMAZING!!! Worth ₹10,499... 100% recommended!!!

In [8]:
sample = sample.lower()

print(sample)

product is amazing!!! worth ₹10,499... 100% recommended!!!

In [9]:
clean_sample = re.sub(r"[^a-zA-Z\s]", " ", sample)

print(clean_sample)

product is amazing    worth                 recommended

In [10]:
clean_sample = re.sub(r"\s+", " ", clean_sample).strip()

print(clean_sample)

product is amazing worth recommended

In [11]:
text = "this product is very good"

tokens = text.split()

print(tokens)

['this', 'product', 'is', 'very', 'good']

In [12]:
import nltk

print(nltk.__version__)

3.10.1

In [13]:
import nltk

nltk.download("punkt")
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\RUSHIKESH\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\RUSHIKESH\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [14]:
from nltk.tokenize import word_tokenize

In [15]:
text = "I don't like this product. Battery life is very poor!"

In [16]:
nltk_tokens = word_tokenize(text)

print(nltk_tokens)

['I', 'do', "n't", 'like', 'this', 'product', '.', 'Battery', 'life', 'is', 'very', 'poor', '!']

In [17]:
review = df["full_review"].iloc[0]

print("Original Review:")
print(review)

tokens = word_tokenize(review)

print("\nTokens:")
print(tokens)

Original Review:
Simply awesome it's really worth every single penny. it works like one ton AC provided that your room has proper ventilation.  I generally keep cooler near to window so that it can pull fresh air from outside and as a result I get very cool air. one more suggestion,  please don't buy cooler which are equipped with a blower fan. Always go for the cooler equipped with metal fan like this one.  In one word, this Compton cooler is Amazing. if you find the review helpful, please thumps up. Happy summer! ????

Tokens:
['Simply', 'awesome', 'it', "'s", 'really', 'worth', 'every', 'single', 'penny', '.', 'it', 'works', 'like', 'one', 'ton', 'AC', 'provided', 'that', 'your', 'room', 'has', 'proper', 'ventilation', '.', 'I', 'generally', 'keep', 'cooler', 'near', 'to', 'window', 'so', 'that', 'it', 'can', 'pull', 'fresh', 'air', 'from', 'outside', 'and', 'as', 'a', 'result', 'I', 'get', 'very', 'cool', 'air', '.', 'one', 'more', 'suggestion', ',', 'please', 'do', "n't", 'buy', 'cooler', 'which', 'are', 'equipped', 'with', 'a', 'blower', 'fan', '.', 'Always', 'go', 'for', 'the', 'cooler', 'equipped', 'with', 'metal', 'fan', 'like', 'this', 'one', '.', 'In', 'one', 'word', ',', 'this', 'Compton', 'cooler', 'is', 'Amazing', '.', 'if', 'you', 'find', 'the', 'review', 'helpful', ',', 'please', 'thumps', 'up', '.', 'Happy', 'summer', '!', '?', '?', '?', '?']

In [18]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\RUSHIKESH\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [19]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words("english"))

In [20]:
list(stop_words)[:20]

['hasn',
 'who',
 'should',
 'such',
 'ours',
 'myself',
 "isn't",
 'why',
 "should've",
 'other',
 'or',
 'needn',
 'and',
 'ma',
 'ain',
 't',
 "weren't",
 'aren',
 'nor',
 'a']

In [21]:
negation_words = {"no", "not", "nor"}

custom_stop_words = stop_words - negation_words

In [22]:
print("not" in custom_stop_words)
print("no" in custom_stop_words)
print("nor" in custom_stop_words)

False
False
False

In [23]:
text = "this product is not good and the battery is very poor"

tokens = word_tokenize(text.lower())

filtered_tokens = [
    word for word in tokens
    if word not in custom_stop_words
]

print(filtered_tokens)

['product', 'not', 'good', 'battery', 'poor']

In [24]:
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

In [25]:
words = ["working", "worked", "works", "playing", "played", "plays"]

for word in words:
    print(word, "→", stemmer.stem(word))

working → work
worked → work
works → work
playing → play
played → play
plays → play

In [26]:
from nltk.stem import WordNetLemmatizer

In [27]:
nltk.download("wordnet")
nltk.download("omw-1.4")

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\RUSHIKESH\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\RUSHIKESH\AppData\Roaming\nltk_data...

True

In [28]:
lemmatizer = WordNetLemmatizer()

In [29]:
words = ["cars", "studies", "products", "batteries"]

for word in words:
    print(word, "→", lemmatizer.lemmatize(word))

cars → car
studies → study
products → product
batteries → battery

In [30]:
import re
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

stop_words = set(stopwords.words("english"))

# Keep negation words because they're important for sentiment
stop_words = stop_words - {"no", "not", "nor"}

In [31]:
def preprocess_text(text):

    # 1. Convert to lowercase
    text = text.lower()

    # 2. Keep English letters and spaces
    text = re.sub(r"[^a-zA-Z\s]", " ", text)

    # 3. Remove extra spaces
    text = re.sub(r"\s+", " ", text).strip()

    # 4. Tokenization
    tokens = word_tokenize(text)

    # 5. Remove stopwords
    tokens = [
        word for word in tokens
        if word not in stop_words
    ]

    # 6. Lemmatization
    tokens = [
        lemmatizer.lemmatize(word)
        for word in tokens
    ]

    # 7. Join tokens back into a sentence
    clean_text = " ".join(tokens)

    return clean_text

In [32]:
sample = "This product is NOT good!!! The batteries are very poor."

processed = preprocess_text(sample)

print("Original:")
print(sample)

print("\nProcessed:")
print(processed)

Original:
This product is NOT good!!! The batteries are very poor.

Processed:
product not good battery poor

In [33]:
original = df["full_review"].iloc[0]

processed = preprocess_text(original)

print("ORIGINAL:")
print(original)

print("\nCLEANED:")
print(processed)

ORIGINAL:
Simply awesome it's really worth every single penny. it works like one ton AC provided that your room has proper ventilation.  I generally keep cooler near to window so that it can pull fresh air from outside and as a result I get very cool air. one more suggestion,  please don't buy cooler which are equipped with a blower fan. Always go for the cooler equipped with metal fan like this one.  In one word, this Compton cooler is Amazing. if you find the review helpful, please thumps up. Happy summer! ????

CLEANED:
simply awesome really worth every single penny work like one ton ac provided room proper ventilation generally keep cooler near window pull fresh air outside result get cool air one suggestion please buy cooler equipped blower fan always go cooler equipped metal fan like one one word compton cooler amazing find review helpful please thump happy summer

In [34]:
df["clean_text"] = df["full_review"].apply(preprocess_text)

In [35]:
df[["full_review", "clean_text"]].head(10)

,full_review,clean_text
0,Simply awesome it's really worth every single ...,simply awesome really worth every single penny...
1,Worth the money . Desert Cooler live up to the...,worth money desert cooler live name bought cro...
2,Worth every penny GREAT packaging by seller. A...,worth every penny great packaging seller impor...
3,Fabulous! Delivery was delayed by two days exc...,fabulous delivery delayed two day except every...
4,Nice product A Good cooler by Crompton. The he...,nice product good cooler crompton height coole...
5,"Super! Can't go wrong with Crompton Brand, In ...",super go wrong crompton brand punjab excellent...
6,Terrific purchase A great cooler in great pric...,terrific purchase great cooler great price com...
7,Classy product Its an awesome product and I am...,classy product awesome product not making fake...
8,Perfect product! Air throw is very good.??????...,perfect product air throw good low noise best ...
9,Its not a cooler its Ac cooler Its been 6 days...,not cooler ac cooler day using cooler room buy...

In [36]:
empty_count = (df["clean_text"].str.strip() == "").sum()

print("Empty cleaned reviews:", empty_count)

Empty cleaned reviews: 0

In [37]:
from nltk.util import ngrams

In [38]:
text = "battery life is not good"

tokens = text.split()

print(tokens)

['battery', 'life', 'is', 'not', 'good']

In [39]:
bigrams = list(ngrams(tokens, 2))

print(bigrams)

[('battery', 'life'), ('life', 'is'), ('is', 'not'), ('not', 'good')]

In [41]:
import sklearn

print(sklearn.__version__)

1.9.0

In [42]:
from sklearn.feature_extraction.text import CountVectorizer

In [43]:
reviews = [
    "product good",
    "product bad",
    "product good good"
]

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(reviews)

In [44]:
print(vectorizer.get_feature_names_out())

['bad' 'good' 'product']

In [45]:
print(X.toarray())

[[0 1 1]
 [1 0 1]
 [0 2 1]]

In [46]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [47]:
reviews = [
    "product is good",
    "product is excellent",
    "product is bad"
]

In [48]:
vectorizer = TfidfVectorizer()

In [50]:
X = vectorizer.fit_transform(reviews)

In [51]:
print(vectorizer.get_feature_names_out())

['bad' 'excellent' 'good' 'is' 'product']

In [52]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(

    max_features=5000,

    ngram_range=(1,2),

    min_df=5,

    max_df=0.90

)

In [53]:
X = tfidf.fit_transform(df["clean_text"])

In [54]:
print(X.shape)

(306316, 5000)

In [55]:
print(tfidf.get_feature_names_out()[:30])

['able' 'absolute' 'absolute rubbish' 'absolutely' 'absolutely fine'
 'absorb' 'absorbing' 'absorption' 'ac' 'accept' 'acceptable' 'accepted'
 'access' 'accessory' 'according' 'according price' 'accurate' 'across'
 'act' 'action' 'activity' 'actual' 'actually' 'adapter' 'adaptor' 'add'
 'added' 'adding' 'addition' 'additional']

In [56]:
reviews = [
    "product good",
    "product bad",
    "product excellent"
]

tfidf = TfidfVectorizer()

X = tfidf.fit_transform(reviews)

print(tfidf.get_feature_names_out())

print(X.toarray())

['bad' 'excellent' 'good' 'product']
[[0.         0.         0.861037   0.50854232]
 [0.861037   0.         0.         0.50854232]
 [0.         0.861037   0.         0.50854232]]

In [57]:
X[0].toarray()

array([[0.        , 0.        , 0.861037  , 0.50854232]])

In [58]:
feature_names = tfidf.get_feature_names_out()

first_review = X[0].toarray()[0]

for word, score in zip(feature_names, first_review):
    if score > 0:
        print(word, ":", round(score, 4))

good : 0.861
product : 0.5085

In [1]:
y = df["sentiment"]

NameError: name 'df' is not defined

In [2]:
print(y.shape)

NameError: name 'y' is not defined

In [3]:
print(y.value_counts())

NameError: name 'y' is not defined